### ISSUE TITLE
Teleporter time & Halcyon seed total price aren't shown to non-host players in multiplayer

### ISSUE THREAD

**Issue by LordVGames** [Goorakh/NoMoreMath#2]
Been using the mod in multiplayer, and my brother noticed that, for him, the seconds to charge the teleporter isn't displayed correctly, and instead shows "(N/A s)" the whole time. I'm the host of the multiplayer sessions, and I see the teleporter time just fine. This also affects the halcyon seed calculations, where he sees $0 while I see the total price just fine.

We are both using the latest version of the mod.

**Comment by Goorakh** [comment]
The holdout zone issue has been fixed in version 1.1.2, I will look into the Halcyon Beacons later.

**Comment by Goorakh** [comment]
Fixed in v2.0.0
