### ISSUE TITLE
HealthbarImmune conflict, breaks player HP

### ISSUE THREAD

**Issue by u-lulu** [Goorakh/NoMoreMath#4]
If this mod and [HealthbarImmune](https://thunderstore.io/package/DestroyedClone/HealthbarImmune/) are both installed, health values are not shown on the player's UI.

![image](https://github.com/user-attachments/assets/ad2611d7-4e37-4dd0-be95-343033e7fa0d)

**Comment by Goorakh** [comment]
Fixed in v2.0.1
